// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GroceryItem struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Quantity       *int      `json:"quantity,omitempty"`
	PurchaseDate   *string   `json:"purchaseDate,omitempty"`
	AddedDate      *string   `json:"addedDate,omitempty"`
	ExpirationDate *string   `json:"expirationDate,omitempty"`
	Price          *float64  `json:"price,omitempty"`
	Materials      []*string `json:"materials,omitempty"`
	Category       *string   `json:"category,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	UserID string `json:"userID"`
}
